# This file is primarily for running locally

services:

  web:
    image: nginx:1.28
    environment:
      - TZ=Europe/Stockholm
    ports:
      - 8088:80
    volumes:
      - ./src:/usr/share/nginx/html
